
# git clone 深度为 3
git:
  depth: 3


language: node_js

node_js:
  - "10"
  - "12"
  - "14"

os:
   - linux
  
cache: npm

install: 
  - npm install


before_script:
  - npm config set loglevel warn

script:
  - npm run ci

after_success:
  - npm run report-coverage